openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/v1/contact-us:
    post:
      summary: '1. Enquiry Mail'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - 'Contact-Us API'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullname:
                  type: string
                  description: 'The fullname for contact us enquiry.'
                  example: 'John Wick'
                email:
                  type: string
                  description: 'The email for contact us enquiry.'
                  example: johnwick@gmail.com
                phone_number:
                  type: string
                  description: 'The phone_number for contact us enquiry.'
                  example: '012342123'
                message:
                  type: string
                  description: 'The message for contact us enquiry.'
                  example: 'lorem ipsum..'
              required:
                - email
                - phone_number
                - message
      security: []
  /api/v1/users:
    post:
      summary: '1. Create an user'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - 'User API'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tmp_user:
                  type: string
                  description: 'The temporary user ID during request OTP.'
                  example: eyJpdiI...
                fullname:
                  type: string
                  description: 'The fullname for register.'
                  example: 'John Wick'
                email:
                  type: string
                  description: 'The email for register.'
                  example: johnwick@gmail.com
                otp_code:
                  type: string
                  description: 'The otp for register.'
                  example: '123456'
                password:
                  type: string
                  description: 'The password for register.'
                  example: abcd1234
                password_confirmation:
                  type: string
                  description: 'The confirmation password.'
                  example: abcd1234
              required:
                - tmp_user
                - fullname
                - email
                - otp_code
                - password
                - password_confirmation
      security: []
    get:
      summary: '5. Get user'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - 'User API'
  /api/v1/users/login:
    post:
      summary: '2. Login an user - Email'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - 'User API'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'The email for login.'
                  example: johnwick@mail.com
                password:
                  type: string
                  description: 'The password for login.'
                  example: abcd1234
              required:
                - email
                - password
      security: []
  /api/v1/otp:
    post:
      summary: '3. Request an OTP'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - 'User API'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'The email for login.'
                  example: johnwick@mail.com
                request_type:
                  type: integer
                  description: 'The request type for OTP.'
                  example: 1
              required:
                - email
                - request_type
      security: []
  /api/v1/otp/resend:
    post:
      summary: '4. Resend an OTP'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - 'User API'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tmp_user:
                  type: string
                  description: 'The temporary user ID during request OTP.'
                  example: eyJpdiI...
                email:
                  type: string
                  description: 'The email for login.'
                  example: johnwick@mail.com
                request_type:
                  type: integer
                  description: 'The request type for OTP.'
                  example: 2
              required:
                - tmp_user
                - email
                - request_type
      security: []
  /api/v1/users/reset-password:
    post:
      summary: '10. Reset Password'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - 'User API'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Can be email or phone number, to perform password reset.'
                  example: johnwick@gmail.com
                identifier:
                  type: string
                  description: 'The unique_identifier from forgot password.'
                  example: WLnvrJw6YYK
                otp_code:
                  type: string
                  description: 'The otp code to verify password reset.'
                  example: '123456'
                password:
                  type: string
                  description: 'The new password to perform password reset.'
                  example: abcd1234
                password_confirmation:
                  type: string
                  description: 'The new password confirmation to perform password reset.'
                  example: abcd1234
              required:
                - email
                - identifier
                - password
                - password_confirmation
      security: []
  /api/v1/users/check-email:
    post:
      summary: '8. Check Email (Pre-request Otp)'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - 'User API'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'email, to prepare for password reset.'
                  example: johnwick@gmail.com
              required:
                - email
      security: []
  /api/v1/users/forgot-password:
    post:
      summary: '9. Forgot Password (Request Otp)'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - 'User API'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'email, to perform password reset.'
                  example: johnwick@gmail.com
              required:
                - email
      security: []
tags:
  -
    name: 'Contact-Us API'
    description: ''
  -
    name: 'User API'
    description: ''
